#!/bin/bash
THEME="/home/gigi/.custom-themes/xmonad-dark-paradise"

# sed -i -e 's/dotspacemacs-themes '\''(.*)/dotspacemacs-themes '\''(spacemacs-dark-paradise)/' $HOME/.spacemacs &

# Change gtk and icon themes
# cp $THEME/gtk/.gtkrc-2.0.mine $HOME/ & 
# sed -i -e 's/gtk-theme-name=.*/gtk-theme-name=dark-paradise/' $HOME/.config/gtk-3.0/settings.ini &
# sed -i -e 's/icon-theme-name=.*/gtk-icon-theme-name=Pop/' $HOME/.config/gtk-3.0/settings.ini &

# cp $THEME/rofi/config $HOME/.config/rofi/ &
# cp $THEME/kitty/kitty.conf $HOME/.config/kitty/ &
# cp $THEME/.Xresources $HOME/ &

 light-locker &
 xmonad &
# feh --bg-fill /home/gigi/.backgrounds/dark-paradise/flamingowall.jpg &
# tint2 &
# nm-applet &
# pa-applet &
# compton &
